sudo: required

services:
  - docker

before_install:
  - gem install package_cloud
  - wget http://mirror.metrocast.net/apache/aurora/0.9.0/apache-aurora-0.9.0.tar.gz

script:
  #- ./build-artifact.sh builder/deb/ubuntu-trusty ./apache-aurora-0.9.0.tar.gz 0.9.0
  - ./build-artifact.sh builder/rpm/centos-6 ./apache-aurora-0.9.0.tar.gz 0.9.0
  #- ./build-artifact.sh builder/rpm/centos-7 ./apache-aurora-0.9.0.tar.gz 0.9.0
  - package_cloud push ssalevan/aurora/el/6 dist/builder/rpm/centos-6/rpmbuild/RPMS/**.rpm
